### ISSUE TITLE
Maintenance mode?

### ISSUE THREAD

**Issue by danmrossi** [treesta1ker/esp32-MobiusBLE#2]
Hi there, i was wondering what "Maintenance" mode actually is?

**Comment by treesta1ker** [comment]
Are you referring to the [example Control code](https://github.com/treesta1ker/esp32-MobiusBLE/blob/fe42212c3b74c4e63bad94c6036330ce7031fc50/examples/Control/Control.ino#L94)?
It's whatever you want it to be.  In the example it just means the "SENSOR_PIN" voltage is within the 2V range and then sets the scene to a specific ID (`sceneId = 1234;`).  That's it really.  The "scene ID" would be specific to your setup and could correspond to anything you wish (maybe something with a minimal speed while you clean the sand bed or trim corals).

**Comment by danmrossi** [comment]
Yeah, how does one find what the different scene ids are?
Sent from my iPhone

On 1 Jul 2024, at 8:10 PM, treesta1ker ***@***.***> wrote:

﻿

Are you referring to the example Control code<https://github.com/treesta1ker/esp32-MobiusBLE/blob/fe42212c3b74c4e63bad94c6036330ce7031fc50/examples/Control/Control.ino#L94>?
It's whatever you want it to be. In the example it just means the "SENSOR_PIN" voltage is within the 2V range and then sets the scene to a specific ID (sceneId = 1234;). That's it really. The "scene ID" would be specific to your setup and could correspond to anything you wish (maybe something with a minimal speed while you clean the sand bed or trim corals).

**Comment by treesta1ker** [comment]
By sniffing the Bluetooth traffic from the Mobius app.
Check out part "(a) Capturing BLE Messages" from [this thread post](https://www.reef2reef.com/threads/controlling-mobius-enabled-vortech-pump-using-0-10v-and-ble.814921/).
